### ISSUE TITLE
v2 changes

### ISSUE THREAD

**Issue by scottnath** [pattern-library/patterns-menu-list#2]
Hi @rebmullin 

So, there's a couple changes that are needed.
1. menu.html
   get rid of this
   - we don't want to include actual output with the module
2. index.js
   move this to main folder ./
   - this allows other modules to include your module with `require('pattern-menu-list')`
3. menu.json
   keep this, but move it
   - you're gonna use this in a test (later, not today.) 
   - Move this file to ./test/fixtures/example.json
4. menu.twig
   keep this, but move it
   -  eventually this will be optional to use, so move it to ./templates/menu.twig
5. parameters
   these should not be defined in your module. so this:
   
   ```
   module.exports = patternsMenu('menu.twig', 'menu.json', 'menu.html');
   ```
   
   becomes this:
   
   ```
   module.exports = patternsMenu;
   ```
6. no data file, just data
   so...now you're gonna get rid of [this line](https://github.com/pattern-library/patterns-menu-list/blob/master/menu/index.js#L5):
   
   ```
   var obj = JSON.parse(fs.readFileSync(filePath, 'utf8')); // want a json object
   ```
   
   and instead of a file, you're just gonna pass your script an object. Which dovetails with the next task...
7. call this from another file and use it!
   So...create some other file which will be something like this:

```
var menuLister = require('/path/to/patterns-menu-list');
var fs = require('fs-extra');

// this could be any template
var myTwigTemplate = '/path/to/menu.twig';

// you could write out this object, get it from a file, get it from another function like pattern-presenter
var obj = JSON.parse(fs.readFileSync('/path/to/menu.json', 'utf8')); 

var dest = '/path/to/some/new/file.html';

var htmlMenu = menuLister(myTwigTemplate, obj, dest);

// this should spit out the final html to the module
console.log(htmlMenu);
```

thank you! as always...let me know if you need anything

scott

**Comment by rebmullin** [comment]
hey @scottnath  - can we close this?

**Comment by scottnath** [comment]
Absolutely!
